pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "TeamCompass"
include(":app")
include(":core")
include(":core:common")
include(":core:model")
include(":core:auth")
include(":core:realtime")
include(":core:telemetry")
include(":core:tactical")
include(":core:data")
include(":core:testing")
include(":core:designsystem")
include(":core:ui")
include(":core:datastore")
include(":core:network")
include(":core:database")
include(":feature:nav")
include(":feature:directories:api")
include(":feature:directories:impl")
include(":feature:calendarsync:api")
include(":feature:calendarsync:impl")
include(":feature:productivity:api")
include(":feature:productivity:impl")
include(":feature:notifications:api")
include(":feature:notifications:impl")
include(":feature:creators:api")
include(":feature:creators:impl")
include(":feature:admin:api")
include(":feature:admin:impl")
include(":feature:workflow:api")
include(":feature:workflow:impl")
include(":feature:search:api")
include(":feature:search:impl")
include(":feature:settings:api")
include(":feature:settings:impl")
include(":feature:support:api")
include(":feature:support:impl")
include(":feature:compliance:api")
include(":feature:compliance:impl")
include(":feature:onboarding:api")
include(":feature:onboarding:impl")
include(":feature:auth:api")
include(":feature:auth:impl")
include(":feature:chats:api")
include(":feature:chats:impl")
include(":feature:teams:api")
include(":feature:teams:impl")
include(":feature:events:api")
include(":feature:events:impl")
include(":feature:marketplace:api")
include(":feature:marketplace:impl")
include(":feature:profile:api")
include(":feature:profile:impl")
include(":feature:tactical:api")
include(":feature:tactical:impl")
include(":infra:firebase")
include(":infra:device")
